### ISSUE TITLE
allow user to override globals in polyscript

### ISSUE THREAD

**Issue by bugzpodder** [pyscript/polyscript#16]
Both pyodide and webR allows user to clear/override globals when executing some code.  This will avoid variable pollution where previous execution defined some variable that still is available in the next execution.  I'd love to see this supported in polyscript.  This also alliows user to pass arbitrary data into the global context.

pyodide:
```
      const globals = pyScript.interpreter.globals.get("dict")();
      await pyScript.interpreter.runPythonAsync(code, { globals });
     // prefer pyScript.runAsync(code, ...); from polyscript
```

webR:
```
    const env = await new webR.REnvironment();
    await webR.evalRVoid(code, { env, captureStreams: false });
```

**Comment by bugzpodder** [comment]
https://github.com/pyscript/polyscript/blob/42762846cd21f6ccb5b89053cd0aa340194db529/esm/interpreter/_python.js#L18C1-L25C3

maybe something like:
```
export const runAsync = (interpreter, code, ...params) => {
    try {
        return interpreter.runPythonAsync(clean(code), ...params);
    }
    catch (error) {
        io.get(interpreter).stderr(error);
    }
};
```

**Comment by WebReflection** [comment]
your suggestion is sync try/catch while using a `runAsync` primitive .. that won't work for sure, but also, you're not using the polyscript primitives there which are `run` and `runAync` ... any reason to that?

**Comment by bugzpodder** [comment]
> 



> your suggestion is sync try/catch while using a `runAsync` primitive .. that won't work for sure, 

my suggestion came directly from the polyscript codebase and I just want to illustrate what I need, which is to have additional params passed into run.  But feel free to ignore it.

> but also, you're not using the polyscript primitives there which are `run` and `runAync` ... any reason to that?

Yes as I illustrated in my initial post I need an empty globals passed into runPythonAsync:
```
const globals = pyScript.interpreter.globals.get("dict")();
await pyScript.interpreter.runPythonAsync(code, { globals });
```

**Comment by WebReflection** [comment]
> my suggestion came directly from the polyscript codebase and I just want to illustrate what I need, which is to have additional params passed into run. But feel free to ignore it.

my suggestion is that if you `runAsync` then you need to *await* the result ... this is not my opinion, this is how async works:

```js
try {
  fetch('fail')
}
catch(nope) {
  // this would never happen
}
```

> I need an empty globals passed into runPythonAsync

any reason you need to do so? this was never the way in PyScript "classic" (IIRC) so I am not sure why you need that instead of having a function that returns whatever you need

**Comment by WebReflection** [comment]
to be more explicit on my point ... your code should look like this one:

```js
export const runAsync = async (interpreter, code, ...params) => {
    try {
        return await interpreter.runPythonAsync(clean(code), ...params);
    }
    catch (error) {
        io.get(interpreter).stderr(error);
    }
};
```

**Comment by WebReflection** [comment]
btw, if that's instead current code (the one you showed) then yes, we have an issue in there!

**Comment by bugzpodder** [comment]
> my suggestion is that if you `runAsync` then you need to _await_ the result ... this is not my opinion, this is how async works:
> 
> ```js
> try {
>   fetch('fail');
>   // nothing throws as you are not awaiting
> }
> catch(nope) {
>   // this would never happen
> }

I think we are mixing thread here.  I just want to pass in additional params into runAsync so it get transferred into pyodide.runPythonAsync, nothing more/less.


> ```
> 
> > I need an empty globals passed into runPythonAsync
> 
> any reason you need to do so? this was never the way in PyScript "classic" (IIRC) so I am not sure why you need that instead of having a function that returns whatever you need

sure but we are talking about polyscript which is the base for pyscript and for other use cases.  I am just saying that it will enable by use case (usage in a react app where I need clean globals).  pyscript can just do whatever it does currently and it won't affect me.

**Comment by WebReflection** [comment]
so ... I think I owe you an apology because indeed you showed code that should've been better on polyscript side ... which is the case now ... the `runAsync` now propagates the error to `io` after awaiting the result of the invoke: bad me, good you!

now, with this latest module, do you still have issues? 'cause now things will throw differently from what you experienced before!

thanks for your patience

**Comment by bugzpodder** [comment]
> so ... I think I owe you an apology because indeed you showed code that should've been better on polyscript side ... which is the case now ... the `runAsync` now propagates the error to `io` after awaiting the result of the invoke: bad me, good you!
> 
> now, with this latest module, do you still have issues? 'cause now things will throw differently from what you experienced before!
> 
> thanks for your patience

no worries thats great runAsync now catching the error properly.  However I mentioned that I just need to pass in additional params in runAsync so I can clear globals when I run.  But no big deal as I have access to the underlying interpreter anyway and can just call 


```
const globals = pyScript.interpreter.globals.get("dict")();
await pyScript.interpreter.runPythonAsync(code, { globals });
```

**Comment by WebReflection** [comment]
I think you are using the tool the right way, but that's also an advanced way ... we try to enable entry level developers, still offering escapes to do more advanced tasks, and you definitively fit in the latter case ... accordingly, I'll close this, but please feel free to open it again if you think there's still something to fix here.

**Comment by JeffersGlass** [comment]
If I'm understanding right, the thought by @bugzpodder here is:

- `runAsync` is a fairly thin wrapper around `runPythonAsync` or `evalRVoid` or similar, as appropriate for the runtime
- But, `runPythonAsync` and `evalRVoid` can take additional parameters (`globals`/`locals` and `options` respectively)
- It would be useful to be able to pass these parameters *through* `runAsync` to the appropriate delegated method

I can see the value in that, and it sounds like this is a practical issue that's been encountered, not a theoretical one, which is nice.

Have I understood right BP?

**Comment by WebReflection** [comment]
@JeffersGlass the abstraction layer for interpreters is kept simple on purpose because not all interpreters expose the same API or features during code evaluation ... on the other hand, we could be smart enough and simply pass extra arguments if provided.

This means that [this signature](https://github.com/pyscript/polyscript/blob/main/esm/interpreter/_python.js#L18-L25) would change as:

```js
export const runAsync = async (interpreter, code, ...args) => {
    try {
        return await interpreter.runPythonAsync(clean(code), ...args);
    }
    catch (error) {
        io.get(interpreter).stderr(error);
    }
};
```

and so would the `run` ... this leaves room for advanced use cases, without us going mental normalizing every possible API of any interpreter that we want now or tomorrow in the project.

@bugzpodder would that work for you?

**Comment by WebReflection** [comment]
you know what ... this takes nothing to be added so I'll just do it as we have already an issue to enable this and it seems reasonable to me.

**Comment by WebReflection** [comment]
The latest polyscript allows passing extra arguments to either `run(core, ...args)` or `runAsync(code, ...args)` for all interpreters in both main and workers.
