### ISSUE TITLE
xworker hooks cannot be used

### ISSUE THREAD

**Issue by bugzpodder** [pyscript/polyscript#20]
Users may need to be able to hook into XWorker runtime.

I've tried to pass in functions to onAfterRun/onAfterRunAsync and got an error.

This may repro: https://bugzpodder.pyscriptapps.com/polyscript-worker-errors-copy/latest/
However the domain is blocked by my computer so I don't know exactly.

Not sure if its webpack specific or not but it seems that the error is just serializing a function to postMessage which doesnt work, makes sense.
<img width="1144" alt="Screenshot 2023-08-29 at 7 38 04 AM" src="https://github.com/pyscript/polyscript/assets/14841421/2a8f1ebc-f31b-4102-a65a-eaada81ac190">

**Comment by WebReflection** [comment]
> I've tried to pass in functions to onAfterRun/onAfterRunAsync and got an error.

As the TypeScript hints, anything Worker related has to be a string. You can't pass functions because you can't pass the main scope down to workers ... this is a Web limitation, not a polyscript one, I am afraid.

**Comment by WebReflection** [comment]
P.S. please feel free to check PyScript next branch, pyscript.core folder, to see how we use worker hooks to bootstrap the module within Workers.
