### ISSUE TITLE
allow users to trap errors from runAsync

### ISSUE THREAD

**Issue by bugzpodder** [pyscript/polyscript#21]
Currently errors are trapped by try/catch statement in runAsync, eg:
```
   runAsync: async (interpreter, code, ...args) => {
        try {
            return await interpreter.doString(clean(code), ...args);
        }
        catch (error) {
            io.get(interpreter).stderr(error);
        }
    },
```

As a polyscript user I would like to have more granular control on the error being returned from runAsync.

The reason is that there are multiple scripts running on the page outputting to different parts of the page and I need to know which script caused the error and what the error is.  Using io seems too restrictive and I want to be able to handle the error more freely.

**Comment by WebReflection** [comment]
> As a polyscript user I would like to have more granular control on the error being returned from runAsync.

that's what the `io` field in `define` is for, you can fine-tune anything you like, like we will do in PyScript soon.

Please see the documentation around `io` field when defining custom types ... you can postMessage the error instead, if that's what you are after, or do anything you like, really ... the `stderr` utility is there exactly to address this use case.

Anything in particular you belive is not working after defining that `io.stderr` yourself?

**Comment by bugzpodder** [comment]
Yes.  If I have two blocks of code I have no idea which one triggered io.stderr.

**Comment by WebReflection** [comment]
it was a PyScript requirement to be able to intercept errors and show these gracefully or in a custom way ... what you are asking is to re-throw the error as it is after invoking stderr which would result into duplicated errors shown in console if you don't define your own `io` field ... hence I am not sure what you are asking ... you can define your own `stderr` and throw errors out of the blue there instead of just logging, or posting these around ... right?

what is it that you are trying to achieve? What is "more granular control" if you can fully control what an error does already?

**Comment by WebReflection** [comment]
on a second though, maybe you want a return value that's not just `undefined` when an error occur? if that's the case, we could think about a solution to that ... but it might require a `Symbol` you should import and check against its validity to disambiguate with the rest of possible return values ... would that work?

```js
import { ERROR } from 'polyscript';

// ...

const result = interpreter.runAsync(stuff);
if (result === ERROR) {
  // do your thing
}
```

**Comment by WebReflection** [comment]
P.S. if you throw in your custom `io.stderr` you would solve your issue ... but dare I say my latest suggestion might be desired for ourselves too ... please let me know if that would work for you too, thanks!

**Comment by bugzpodder** [comment]
ok thats an interesting proposition, throwing in io.sterrr.  probably would work for my case..

**Comment by bugzpodder** [comment]
If I have two blocks of code I want the errors to be displayed next to each piece of code.  Thats the use case i am trying to aim for.

**Comment by WebReflection** [comment]
> but I am not sure how that could ever look like.

actually I do ... `beforeRunAsync` hook gives you a way to store anywhere the current element id, and you can use that info to reach the place where the error occurred ... as you use `async` results might vary because if you invoke 2 callbacks simultaneously, first come, first serve .... if you don't though, you're good.

**Comment by bugzpodder** [comment]
> the question though is: why do you use multiple scripts at all? each script bootstraps a runtime a part, if the env or the config is different, but you can always combine all of them into one script, which is ideal for both you and this project to handle.

I have multiple charts (eg matplotlib) and each chart is a piece of python code.  If something wrong with the code I would show an error in place of the chart.  Combining them won't help because of variable conflation and error handling.

**Comment by WebReflection** [comment]
but do you need those charts in main? they will block and if you try to parallelize these these would block way more ... if you use workers then you have `display` to show either results or error, if you don't you should resolve each chart one after the other so you won't have issues in there neither ... I think you are, however, mixing too much JS, main, and pyodide on main ... it can work, but your logic is screaming for issues to me, either out of blocked thread, or out of indirections to handle your use cases. I would instead use a worker, 1 to many targets, and store files as a config for the worker so you never block and each chart can be shown one after the other.

**Comment by WebReflection** [comment]
P.S. to explain where I come from, multiple PyScript "classic" on a page never really worked by design ... hence my questioning around why suddenly you want to do that ... is it really needed?

**Comment by bugzpodder** [comment]
Currently workers doesn't work in my app (due to the crossOriginIsolated headers being too strict, no SharedArrayBuffer access) so yes I am using main-thread and it works fine for me.  

I could use display to show the results, but not all errors are in user land.  For example there is a typo in the code and pyodide complains, or there are some OOM issues.

I've able to render 12 charts on the main thread no problem, with 100k points each.  Not ideal but it works, and perf is not that bad.

Yes all chart code is resolved one after another.

**Comment by bugzpodder** [comment]
Here is a screenshot of what I am building.  This is not a fake screenshot but the real product looks more or less similar, has polyscript/pyodide + webR support and it works reasonably well:

<img width="856" alt="Screenshot 2023-08-29 at 12 18 19 PM" src="https://github.com/pyscript/polyscript/assets/14841421/79679198-515b-4f73-a57a-8b9b0c15826a">

**Comment by WebReflection** [comment]
1. this is amazing
  2. how do you include webR? I've tried myself but it was lacking a few primitives, most importantly, it was lacking sync code execution ... did you just for this and added webR out of async features only? ... or did you just use a diffente webR I tried?

thanks!

**Comment by bugzpodder** [comment]
here is my webR implementation: https://pyscript.com/@bugzpodder/divine-hat-copy/latest

I understand there was a big debate around async vs sync python code, but I really didn't try to understand the details so I can't help beyond this.  But it sounds like you are right and I am only using async features only ie in my demo i just did ` await webR.evalRVoid(code);`

To be clear here are my feature requirements:
- support as many libraries as possible (webR and pyodide takes care of that, I needed to write a custom regex parser to parse packages and install them)
- be able to run multiple code blocks and do canvas/svg rendering targeting different DOM elements for each code block 
- be able to catch and display errors in each code block separately (this issue)
- Be able to have arbitrary input data like a dataframe into the python/webR environment

**Comment by JeffersGlass** [comment]
> ...I needed to write a custom regex parser to parse packages from code blocks and install them

Slightly off-topic, so apologies, but @bugzpodder if you're inspecting code to import packages, you may find Pyodide's [loadPackagesFromImports()](https://pyodide.org/en/stable/usage/api/js-api.html#pyodide.loadPackagesFromImports) useful.

**Comment by bugzpodder** [comment]
> > ...I needed to write a custom regex parser to parse packages from code blocks and install them
> 
> Slightly off-topic, so apologies, but @bugzpodder if you're inspecting code to import packages, you may find Pyodide's [loadPackagesFromImports()](https://pyodide.org/en/stable/usage/api/js-api.html#pyodide.loadPackagesFromImports) useful.

So actually looking at this right now (and previously) and honestly it's super confusing between this and micropip.  But my understanding is that for custom packages (eg plotly) you'll need micropip.install.  eg 'seaborn' won't work with loadPackagesFromImports but works with micropip.  There is a find_imports in pyodide.code but AFAIK it acts similar to a regex which I already have thanks to a previous PR in pyscript.

**Comment by bugzpodder** [comment]
The only thing micropip.install won't work is for custom modules (eg if you have import pyscript, pyodide, pyodide_js, etc) and modules from python stdlib which I hard coded.  it would be nice to remove the stdlib entries.

Also some packages have different imports and package names, eg sklearn vs scikit-learn, or some underscore vs dash differences.
