### ISSUE TITLE
[enhancement] Allow non-URL for XWorker

### ISSUE THREAD

**Issue by bugzpodder** [pyscript/polyscript#23]
Today XWorker requires you to serve a worker file where it tries to fetch.  It might be reasonable to support some other use cases like passing in content of the worker directly somehow.  

Also slightly related, Hook class is not exported but it seem to add a little bit of extra functionality to the XWorker, like `codeBeforeRunWorker, codeBeforeRunWorkerAsync, codeAfterRunWorker, codeAfterRunWorkerAsync`

**Comment by WebReflection** [comment]
we're planning to do it better .. you specify any `worker` empty attribute and the content of the script will be forwarded as worker stuff, which basically addresses your use case in a different way ... right?

```html
<script type="pyodide" worker>
  print("hello from a worker")
</script>
```

would that be it?

about exposing hooks, you need a custom type and I gave you already a way to have no type and a way to define an interpreter ... that's not a priority for us at the moment but cn you tell me what you are missing or trying to do?

**Comment by bugzpodder** [comment]
```
<script type="pyodide" worker>
  print("hello from a worker")
</script>
```
that's great if it works.  Hopefully it works out of box with XWorker constructor.

```
about exposing hooks, you need a custom type and I gave you already a way to have no type and a way to define an interpreter ... that's not a priority for us at the moment but cn you tell me what you are missing or trying to do?
```
NP just asking if its intended or not.  I don't need anything, was just playing around with it.

**Comment by WebReflection** [comment]
XWorker is an extend of Worker … you can pass a blob URL instead of a static file and that would do already

**Comment by WebReflection** [comment]
FYI the `worker` attribute, as mentioned, is now part of `0.2.x` release which is live since this morning:
https://github.com/pyscript/polyscript/pull/26
