### ISSUE TITLE
support html5_canvas_backend in worker

### ISSUE THREAD

**Issue by bugzpodder** [pyscript/polyscript#24]
WebR uses OffscreenCanvas to support canvas renderings.  Polyscript's worker doesn't do this so not sure what can be done here:
https://github.com/pyodide/matplotlib-pyodide/

```
import matplotlib
import numpy as np
matplotlib.use("module://matplotlib_pyodide.html5_canvas_backend")
import matplotlib.cm as cm
from matplotlib import pyplot as plt
delta = 0.025
x = y = np.arange(-3.0, 3.0, delta)
X, Y = np.meshgrid(x, y)
Z1 = np.exp(-(X**2) - Y**2)
Z2 = np.exp(-((X - 1) ** 2) - (Y - 1) ** 2)
Z = (Z1 - Z2) * 2
plt.figure()
plt.imshow(
Z,
interpolation="bilinear",
cmap=cm.RdYlGn,
origin="lower",
extent=[-3, 3, -3, 3],
vmax=abs(Z).max(),
vmin=-abs(Z).max(),
)
print("showing")
plt.show()
```

**Comment by WebReflection** [comment]
polyscript supports real-main canvas out of real-main references ... not sure what you are asking here

**Comment by bugzpodder** [comment]
> polyscript supports real-main canvas out of real-main references ... not sure what you are asking here

ok I'll test it.

**Comment by bugzpodder** [comment]
Here is an repo: 

https://bugzpodder.pyscriptapps.com/polyscript-worker-copy-19536/latest/ [worker version]
https://pyscript.com/@bugzpodder/polyscript-worker-copy-19536/latest [non-worker version]
There is an error in the worker but seems to work on the main thread.
Something did happen and you can see a "Figure 1" in the worker demo

**Comment by WebReflection** [comment]
if the error is about that lib using `from js import document` you can patch the global env with `js.document = xworker.window.document` and hopefully call it a day.
