### ISSUE TITLE
reading sync values from js is slightly off

### ISSUE THREAD

**Issue by bugzpodder** [pyscript/polyscript#30]
worker: https://bugzpodder.pyscriptapps.com/xworker-sync-returns-string-copy-copy-copy/latest/

function returning string works but obj/arr seems to be empty.
cannot handle values (eg arr/obj) directly

**Comment by WebReflection** [comment]
That index has no Python content, I’m not sure what I’m looking at

**Comment by WebReflection** [comment]
Moreover, there’s no worker attribute in the tag …

**Comment by bugzpodder** [comment]
@WebReflection 
In the worker code, I am defining the following sync functions:
```
def getArr():
    return ['arr1', 'arr2']

def getStr():
    return 'str1'

def getObj():
    return {'obj': 'objVar'}

xworker.sync.getArr = getArr
xworker.sync.getStr = getStr
xworker.sync.getObj = getObj
```
in JS I am reading them:
```
async function output() {
            console.log('getArr', await xworker.sync.getArr())
            console.log('getObj', await xworker.sync.getObj())
            console.log('getStr', await xworker.sync.getStr())
            document.getElementById('output').innerText = JSON.stringify(
                {
                    'getArr': await xworker.sync.getArr(),
                    'getObj': await xworker.sync.getObj(),
                    'getStr': await xworker.sync.getStr(),
                }
            )            

        }
        ```
        
        and the output is:
        ```
        getArr {}
        getObj {}
        getStr str1
        ```
        it seems like string works but objects/array just returns an empty object

**Comment by WebReflection** [comment]
to_js is what you’re after here … if your utility is meant to survive postMessage dance you need to return or travel JS objects or arrays … I can intercept remote calls as parameters and use transform there, I can’t know upfront what a function, from the outer world, returns. If the invoke happens in that worker code, it’s too late for poly script to convert that Python thing to something else **after** postMessage happens … in short: passing arguments to sync function happens **before** data travels, invoking and handling results from the outer world happens **after** … use to_js() there for utilities meant to be invoked at distance or add to sync lambas that do that for the generic utility you’re exporting

**Comment by WebReflection** [comment]
btw, I’ll try to see if there’s any magic I can add automatically but I think the issue is well understood and described in its “why that happens” and I’m not sure there’s much I can do there, but I’ll try (not immediately though)

**Comment by bugzpodder** [comment]
to_js on which variable? it doesn't seem to work as console.log just show blank objects.  here is a new version: https://bugzpodder.pyscriptapps.com/xworker-sync-returns-string-copy-copy-copy-copy/latest/

**Comment by WebReflection** [comment]
all methods that returns something should make that something JS compatible https://pyodide.org/en/stable/usage/api/js-api.html#pyodide.ffi.PyProxy.toJs

**Comment by bugzpodder** [comment]
@WebReflection it only works in main thread where you interact with pyodide directly: 
https://pyscript.com/@bugzpodder/xworker-sync-returns-string-copy-copy-copy-copy/latest

It does not work when coincident is involved with xworker.sync
https://bugzpodder.pyscriptapps.com/xworker-sync-returns-string-copy-copy-copy-copy/latest/

**Comment by WebReflection** [comment]
I’m afraid I won’t have time to work on this for a few days

**Comment by WebReflection** [comment]
Latest MR uses `transform` (when available) before serializing values back which *should* fix your issue here.
