### ISSUE TITLE
Export more internals to the extending world

### ISSUE THREAD

**Issue by WebReflection** [pyscript/polyscript#35]
In this MR https://github.com/pyscript/pyscript/pull/1698 there are various imports coming directly from whatever utility this module exports.

This works at build time but ...

  * CDNs trying to compile the thing at runtime mostly fail due unreachable code from their setup
  * grab one utility is a hint, grab dozens is a no-go ... we're not at "dozen" count yet, but we're getting closer
  * there's room to factor out also other logical parts, most notably the config parsing dance which is hidden behind an unreachable closure

### Brainstorming

  * this module should just publish more stuff from the index
  * this module could have a `foreign-utils.js` explicit export that exports all the things any other dependent module might want to use

Low priority for now, but definitively something to consider in the near future, for both *PyScript* and other possible projects based on *polyscript*.

**Comment by WebReflection** [comment]
I think until PyScript is in heavy development and RC this won't be super useful as we don't know yet how many internal things we should expose and *rollup* is working just fine right now.

**Comment by WebReflection** [comment]
flagging as won't fix and 3rd party until it's clear what we need to expose (effectively de-prioritizing this).

**Comment by e-nikolov** [comment]
@WebReflection I'm not sure if this is relevant to this issue, but some of the typescript typings are missing values.

- XWorker() returns a default Worker() which is missing the .sync
- XWorker()'s options argument is missing the `async` option
- Hook does not seem to be exported or at least I can't figure out how to import it. Everything I've tried results in errors

**Comment by WebReflection** [comment]
hooks are well documented in *PyScript* but probably not here ... for anything else, I am not a TS expert and JSDoc TS is used in here, if you feel like helping out with types please file a PR but definitively any of this is relevant to this issue.

**Comment by WebReflection** [comment]
This was actually fixed via the `polyscript/exports` entry in the package.json
