### ISSUE TITLE
JS Function Method with Python List as Argument Fails in Worker

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/polyscript#60]
Open the following page in your favorite COI-enabled dev server. The code works in the main thread, but fails in a worker:
```html
<!doctype html>
<html lang="en">
    <head>
        <title>Polyscript</title>
        <script type="module" src="https://cdn.jsdelivr.net/npm/polyscript"></script>
    </head>
    <body>
        <script>
            function aFunc(myArray) {
                console.log(myArray[0], myArray[1])
            }
        </script>
        <script type="module">
            import { XWorker } from "https://cdn.jsdelivr.net/npm/polyscript";

            const w = new XWorker("./workertest.py", { type: "pyodide"});
        </script>
    </body>
</html>
```
```py
import polyscript

f = polyscript.xworker.window.aFunc
print(f([1,2]))
```

Specifically, there error I see is:
```
pyodide.ffi.JsException: TypeError: 'set' on proxy: trap returned falsish for property 'length'
```
This (very similar) code runs fine in Pyodide (0.24.1) in the main thread, or in a <script type="pyodide"> tag in PolyScript:
```html
<script type="pyodide">
    import js

    f = js.aFunc
    print(f([1,2]))
</script>
```

---

### Context

First, you might have noticed that grabbing polyscript.xworker.window is basically [what PyScript does in `magic_js`](https://github.com/pyscript/pyscript/blob/88fa82c61af29dc370a373ee17c091fdf18462a2/pyscript.core/src/stdlib/pyscript/magic_js.py). This is no accident, I was working on getting matplotlib to work in workers in PyScript, but am attempting to follow the issue upstream.

Second: if the issue I was trying to solve was code I controlled, the problem can be solved by manually converting the Python list `[1,2]` into a JavaScript array inside `worker.py`.

```py
import polyscript
from pyodide.ffi import to_js

f = polyscript.xworker.window.aFunc
print(f(to_js([1,2])))
```

*HOWEVER* the original code is not code I control, it's [code within the `matplotlib-pyodide` backend](https://github.com/pyodide/matplotlib-pyodide/blob/bf18793af30d162463a23ecd475bad40c0c671d5/matplotlib_pyodide/browser_backend.py#L176) that gets Matplotlib working in the browser, which passes a list to `canvas.setLineDash()`.

From my understanding, the same code Python code should work in the main thread and in workers, generally, with the exception of some dances around some global objects (document, `devicePixelRatio`, etc) needing to be brought in via xworker. Those exceptions I could figure out, but this one is stumping me. 

Finally, as usual, I can't tell if this is an actual *"bug"* or just something I don't understand about js Proxies. Apologies in advance if it's the latter.

**Comment by WebReflection** [comment]
the `transform` interpreter helper/utility is there to avoid these issues and it's used per each argument and each return value ... it'd be great to reproduce the smallest failing kind of situation, as I think that's a pyodide gotcha, not a polyscript one.

**Comment by JeffersGlass** [comment]
I can't think of a smaller failing example than the one I've given above, unfortunately: a single JS function, when called from Pyodide in a worker, doesn't proxy it's arguments correctly if they're not primitive types.

The same functionality works fine in vanilla Pyodide - which does the proxying proxies all arguments correctly, but it's failing in PolyScript in a worker - you can try my second example above:
```py
<script type="pyodide">
    # This works fine
    import js

    f = js.aFunc
    print(f([1,2]))
</script>
```
So... I'm not sure how to reduce this any further. But maybe there's something I'm not seeing.

**Comment by WebReflection** [comment]
oops, you are right, that was a small example already ... the fact vanilla pyodide works tells me little as that's not via postMessage ... I still think it's pyodide not doing the right thing there with arrays, while dicts are passed just fine. I will try to investigate a bit more, thanks.

**Comment by WebReflection** [comment]
I was going nuts understanding why args where not converted ... but you're not using `sync`, you are accessing directly the globally leaked main function ... i.e.

```html
<!doctype html>
<html lang="en">
    <head>
        <title>Polyscript</title>
        <script type="module" src="../core.js"></script>
    </head>
    <body>
        <script type="module">
            import { XWorker } from "../core.js";

            const { sync } = new XWorker("./array.py", { type: "pyodide"});
            sync.aFunc = myArray => {
                console.log(myArray[0], myArray[1]);
            };
        </script>
    </body>
</html>
```

```python
import polyscript

f = polyscript.xworker.sync.aFunc
print(f([1,2]))
```

this would work without any issue ... so the issue there is that I think coincident is not using the `transform` proxy feature when it comes to `window` export ... I need to dig deeper but today I am sick so please don't hold your breath.

**Comment by WebReflection** [comment]
yup, actually doing this would work `f(pyodide.ffi.to_js([1,2]))` so indeed there is something I am not doing right with `window` proxy ...

**Comment by WebReflection** [comment]
fixed ... now I go to sleep :wave:

**Comment by WebReflection** [comment]
worth saying that fixing this fixed also the need to wrap callbacks for listeners in workers ... win-win?

**Comment by JeffersGlass** [comment]
Hope you get to rest up this weekend and feel better!

> worth saying that fixing this fixed also the need to wrap callbacks for listeners in workers 

Definitely a win! Thanks for looking into all this.
