### ISSUE TITLE
Add Support for Micropython Packages

### ISSUE THREAD

**Issue by JeffersGlass** [pyscript/polyscript#62]
As far as I'm aware, Polyscript doesn't currently support [installing packages](https://docs.micropython.org/en/latest/reference/packages.html) using `mip` or similar. Having the ability to install packages from [micropython-lib](https://github.com/micropython/micropython-lib) or from external URLs would be very handy, the same way that's possible for Pyodide, and possibly using the same `packages` key in the config.

I don't know what this would require from Micropython upstream, just that it would be a useful feature for me.

**Comment by WebReflection** [comment]
IIRC @antocuni told me this is not possible unless you re-compile MicroPython with mentioned modules explicitly part of the build so I think, as much as I'd love this to happen, that we can't do that until we ship a WASM based compiler that is capable of building in the browser the desired version of the module ... which seems a bit more like 2028 or later to me.

**Comment by antocuni** [comment]
> IIRC @antocuni told me this is not possible unless you re-compile MicroPython with mentioned modules explicitly part of the build

I think this is true only for "extension modules" written in C (and AFAIK the only one is ulab).

Pure Python modules should be installable using `mip`.

**Comment by WebReflection** [comment]
@antocuni thanks ... and @JeffersGlass ... welp ... https://github.com/pyscript/polyscript/pull/63

there's no such thing as `mip` module in MicroPython targeting WASM at the moment.

**Comment by JeffersGlass** [comment]
Thanks for looking into it @WebReflection !

**Comment by WebReflection** [comment]
This issue has been addressed via this MR: https://github.com/pyscript/polyscript/pull/73
