### ISSUE TITLE
Juste a question 

### ISSUE THREAD

**Issue by patfrench** [pyscript/polyscript#9]
Hi 
What's the difference between pyscript and polyscript?
I've used both, but as I'm a beginner I can't see any difference.

Thanks you

**Comment by WebReflection** [comment]
early days to show concrete differences but pyscript (next, WIP) is going to use polyscript to offer many more utilities and simplifications while polyscript is meant to be kept as lightweight core for Pyodide, Micropython, Wasmoon and Ruby (wasm-wasi) or more in the future, providing only the most basic things to enable these interpreter and let PyScript, or the community, build custom types on top.

**Comment by WebReflection** [comment]
P.S. this would've been better as discussion in PyScript but as there's no action to take in here I'll close it, hoping that's OK.
